#pragma once

#include <windows.h>

constexpr UINT SCI_GETLENGTH = 2006;
constexpr UINT SCI_GETCURRENTPOS = 2008;
constexpr UINT SCI_GETSELECTIONSTART = 2143;
constexpr UINT SCI_GETSELECTIONEND = 2145;
constexpr UINT SCI_SETSEL = 2160;
constexpr UINT SCI_GETSELTEXT = 2161;
constexpr UINT SCI_REPLACESEL = 2170;
constexpr UINT SCI_GETTEXT = 2182;
constexpr UINT SCI_GETCOLUMN = 2129;
constexpr UINT SCI_POINTXFROMPOSITION = 2164;
constexpr UINT SCI_LINEFROMPOSITION = 2166;
constexpr UINT SCI_POSITIONFROMLINE = 2167;
constexpr UINT SCI_TEXTWIDTH = 2276;
constexpr UINT SCI_POSITIONBEFORE = 2417;

constexpr int STYLE_DEFAULT = 32;
